data1<-read.csv("BTPFINAL1.csv")
plot(data1$wait)

library(ggplot2)
ggplot(Roamingtime, aes(Roamingtime ,..density..))+ geom_histogram(fill="blue",color="red",alpha = 0.5,bins =100) + geom_density()

library(fitdistrplus)
descdist(data1$shop, boot = 1000)


fp = fitdist(data1$roam,"normal")

summary(fln)
mean(data1$roam)
MYDATA<-read.csv("BTPFINALDATA.csv")
library(ggplot2)
ggplot(MYDATA$., aes(MYDATA. ,..density..))+ geom_histogram(fill="blue",color="red",alpha = 0.5,bins =100) + geom_density()
MYDATA<-read.csv("BTPFINALDATA.csv")
library(ggplot2)
ggplot(MYDATA$Interarrivals, aes(MYDATA$Interarrivals ,..density..))+ geom_histogram(fill="blue",color="red",alpha = 0.5,bins =100) + geom_density()
class(MYDATA$Interarrivals)
ggplot(MYDATA, aes(MYDATA$Interarrivals ,..density..))+ geom_histogram(fill="blue",color="black",alpha = 0.5,bins =50) +xlab("Interarrival Time(min)")+ylab("Density")+ggtitle("Interarrivals time distribution")
data<-c(MYDATA[1:400,])
str(data)
ggplot(data, aes(data$Interarrivals ,..density..))+ geom_histogram(fill="blue",color="black",alpha = 0.5,bins =50) +xlab("Interarrival Time(min)")+ylab("Density")+ggtitle("Interarrivals time distribution")
MYDATA<-read.csv("BTPFINALDATA.csv")
ggplot(MYDATA, aes(MYDATA$Interarrivalsn ,..density..))+ geom_histogram(fill="blue",color="black",alpha = 0.5,bins =50) +xlab("InterarrivalTime(min)")+ylab("Density")+ggtitle("Evening Interarrivals time distribution")
ggplot(MYDATA, aes(MYDATA$Interarrivalsa ,..density..))+ geom_histogram(fill="blue",color="black",alpha = 0.5,bins =50) +xlab("Interarrival Time(min)")+ylab("Density")+ggtitle("Afternoon Interarrivals time distribution")
MYDATA<-read.csv("BTPFINALDATA.csv")
ggplot(MYDATA, aes(MYDATA$Roaming.Time ,..density..))+ geom_histogram(fill="blue",color="red",alpha = 0.5,bins =75) +xlab("Roaming Time(min)")+ylab("Density")+ggtitle("Roaming/Shopping time distribution")+geom_density()
ggplot(MYDATA, aes(MYDATA$Roamingtimea ,..density..))+ geom_histogram(fill="blue",color="red",alpha = 0.5,bins =75) +xlab("Roaming Time(min)")+ylab("Density")+ggtitle("Roaming time distribution")+geom_density()

MYDATA<-read.csv("BTPFINALDATA.csv")
ggplot(MYDATA, aes(MYDATA$ST ,..density..))+ geom_histogram(fill="blue",color="red",alpha = 0.5,bins =75) +xlab("Service Time(min)")+ylab("Density")+ggtitle("Service time distribution")
MYDATA<-read.csv("BTPFINALDATA.csv")
library(ggplot2)
frame1<-MYDATA$Interarrivalsa
frame2<-MYDATA$Interarrivalsn
frame<-rbind(frame1,frame2)

ggplot(frame,aes(length, fill = veg)) + geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')
p1<-hist(MYDATA$Interarrivalsa,fill="blue",color="red",alpha = 0.5,bins =75)
p2<-hist(MYDATA$Interarrivalsn,fill="GREEN",color="red",alpha = 0.5,bins =75)
plot( p1, col=rgb(0,0,1,1/4), xlim=c(0,5))
plot( p2, col=rgb(1,0,0,1/4), xlim=c(0,5), add=T)
par(mar=c(3, 4, 3, 2) + 0.1) 
set.seed(100) 
hist2(MYDATA$Interarrivalsa,MYDATA$Interarrivalsn,breaks = 50)
install.packages("hplot")
install.packages("squash")
library(squash)
par(mar=c(3, 4, 3, 2) + 0.1) 
set.seed(100) 
hist2(MYDATA$Interarrivalsa,MYDATA$Interarrivalsn,breaks = 50)
plot(p1,col="green",density=50,angle=135,add=TRUE)
plot(p2,col="blue",density=50,angle=45,add=TRUE)